variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
    - build:theme
    - build
    - deploy
  
build:pages:
  stage: build
  image: registry.gitlab.com/pages/hugo/hugo_extended:0.89.4
  script:
    - hugo --minify
  artifacts:
    paths:
      - public

pages:
  stage: deploy
  dependencies:
    - build:pages
  script:
    - find public -type f -iregex '.*\.\(htm\|html\|txt\|text\|js\|css\|json\)$' -execdir gzip -f --keep {} \;
  artifacts:
    paths:
      - public
  only:
    - master