# Plugins
gems:             ['jekyll-paginate']

# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            SWR
tagline:          Adaptation de Savage Worlds à Star Wars
description:      "Adaptation du JDR Savage Worlds à l’univers de Star Wars"
url:              https://swr.ght1pc9kc.fr
locale:           fr_FR
img_dir:          /assets/img/

author:
  name:           'Marthym'
  url:            https://git.framasoft.org/marthym

paginate:         5

# Custom vars
version:          1.1.1

github:
  repo:           https://git.framasoft.org/sw-redemption

sass:
    style:        compressed