---
baseURL: "https://swr.ght1pc9kc.fr/"
languageCode: "fr-fr"
title: "Star Wars Redemption - JDRA"
theme: "binario"

author:
  name: Marthym

params:
  description: >
    Star Wars Redemption est un jeux de rôle papier amateur (jdra ou jdrp), adapté à partir de JDR générique Savage Worlds et basé sur l’univers de Star Wars.
    Il est composé d’un livre de base pour les joueurs et les MJs ainsi que de plusieurs scénarions et campagnes.
  mainMenuAlignment: right
  customCSS: 
    - /css/swr.css
  entry:
    meta:
      - date
      - categories
  share:
    reddit: true

outputs:
  home:
    - HTML
    - RSS
